In [ ]:
# .csv 파일 이해

In [1]:
%%writefile sample1.csv
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three

Writing sample1.csv

In [4]:
# csv를 판다스로 읽어 들이기
import pandas as pd

df_sample = pd.read_csv("sample1.csv")
df_sample
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c1      3 non-null      int64
 1    c2     3 non-null      float64
 2    c3     3 non-null      object
dtypes: float64(1), int64(1), object(1)
memory usage: 204.0+ bytes

In [6]:
%%writefile sample.json

[
    {
      "id": "A001",
      "city": "Tokyo",
      "country": "Japan",
    },
    {
      "id": "B012",
      "city": "Jerusalem",
      "country": "Isreal",
    },
    {
      "id": "C123",
      "city": "Busan",
      "country": "South Korea",
    }
]

Overwriting sample.json

In [ ]:
# JSON은 JavaScript Object Notation의 약자로,
# 데이터를 구조화하여 저장하거나 전송할 때 사용하는 포맷
# 주로 웹에서 클라이언트와 서버 간 데이터 교환에 사용

# 가볍고 텍스트 기반이라 사람이 읽고 쓰기 쉬움
# 대부분의 프로그래밍 언어에서 쉽게 읽고 생성 가능
# **키-값 쌍(key-value pair)**으로 구성된 데이터 구조 사용

df_json = pd.read_json("sample.json")

df_json.info()
df_json.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       3 non-null      object
 1   city     3 non-null      object
 2   country  3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes

          id   city country
count      3      3       3
unique     3      3       3
top     A001  Tokyo   Japan
freq       1      1       1

In [8]:
# 웹에서 json 가져오기
url = "https://jsonplaceholder.typicode.com/users"
df_json = pd.read_json(url)

df_json.head()

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

In [9]:
# 데이타 프레임을 json 으로 변환 및 저장
import pandas as pd

data = {
        '이름': ['John', 'Doe', 'Jane'],
        '나이': [30, 25, 28],
        '성별': ['남성', '남성', '여성']
        }

df = pd.DataFrame(data)

print(df.head())

#데이타프레임을 json 으로 바꿈
json_data = df.to_json(orient="records",indent=4)
print(json_data)

# 데이타 프레임을 JSON 파일로 바로 저장
# 각 행을 JSON 객체로 변환 (리스트 형태)
# df.to_json('행기준.json', orient="records",force_ascii=False,indent=4)
# df.to_json('열기준.json', orient="columns",force_ascii=False,indent=4)

     이름  나이  성별
0  John  30  남성
1   Doe  25  남성
2  Jane  28  여성
[
    {
        "\uc774\ub984":"John",
        "\ub098\uc774":30,
        "\uc131\ubcc4":"\ub0a8\uc131"
    },
    {
        "\uc774\ub984":"Doe",
        "\ub098\uc774":25,
        "\uc131\ubcc4":"\ub0a8\uc131"
    },
    {
        "\uc774\ub984":"Jane",
        "\ub098\uc774":28,
        "\uc131\ubcc4":"\uc5ec\uc131"
    }
]